steps:
  - label: ":nx: Run many"
    command: |
      npm install

      npx nx run-many -t lint test build
      npx nx affected -t lint build test

      echo $$NX_BASE
      echo $$NX_HEAD

      poop

    plugins:
      - secrets:
          variables:
            GRAPHQL_API_TOKEN: GRAPHQL_API_TOKEN
      - praneetloke/nx-set-shas
